version: "3"

tasks:
    generate:
        aliases:
            - gen
        desc: "Generate code from protobuf files"
        cmds: protoc --go_out=./internal/gen/ssov1 --go_opt=paths=source_relative \
            --go-grpc_out=./internal/gen/ssov1 --go-grpc_opt=paths=source_relative \
            ./contracts/auth.proto
        cmds: docker run -d \
            -p 27017:27017 \
            --name dev-mongo \
            -e MONGODB_INITDB_ROOT_USERNAME=sso-user \
            -e MONGODB_INITDB_ROOT_PASSWORD=sso-password \
            -v data-vol:/data/db \
            mongo:latest